# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-03-18 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20180522_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='help_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='Help text'),
        ),
        migrations.AlterField(
            model_name='form',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Slug'),
        ),
    ]
